set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER C:/msys64/mingw64/bin/gcc.exe)
set(CMAKE_CXX_COMPILER C:/msys64/mingw64/bin/g++.exe)
set(CMAKE_MAKE_PROGRAM C:/msys64/mingw64/bin/mingw32-make.exe)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)